### PR TITLE
produceBlockV3 call should send `execution_payload_blinded` value as boolean.

### LINKED ISSUE #6176: Nimbus CL < > Lodestar VC incompatibility
### Describe the bug

We are in the process to test cross beacon <> validator client compatibility, and found a bug when testing nimbus CL with lodestar VC. 

Lodestar reports:
```sh
Apr-05 14:25:06.155[]                error: Error proposing block slot=29, validator=0xb05c…679b - JSON expected key slot is undefined - Failed to produce block
Error: JSON expected key slot is undefined - Failed to produce block
    at ContainerType.fromJson (/usr/app/node_modules/@chainsafe/ssz/src/type/container.ts:347:15)
    at Object.fromJson (file:///usr/app/packages/api/src/utils/types.ts:156:44)
    at Object.fromJson (file:///usr/app/packages/api/src/utils/types.ts:198:15)
    at Object.fromJson (file:///usr/app/packages/api/src/beacon/routes/validator.ts:778:91)
    at Object.request [as produceBlockV3] (file:///usr/app/packages/api/src/utils/client/client.ts:91:50)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlockProposingService.produceBlockWrapper (file:///usr/app/packages/validator/src/services/block.ts:205:17)
    at BlockProposingService.createAndPublishBlock (file:///usr/app/packages/validator/src/services/block.ts:144:29)
    at async Promise.all (index 0)
```

Nimbus reports:
```sh
nothing out of the ordinary
```

Snooper between cl <> vc reports:
```sh
nothing out of the ordinary
```

### Expected behavior

I would expect all client combinations would work. 

### Steps to reproduce

config.yaml: 
```yaml
participants:
  - cl_type: nimbus
    vc_type: lodestar
additional_services:
  - dora
snooper_enabled: true
global_log_level: debug
```

`kurtosis run github.com/kurtosis-tech/ethereum-package --args-file config.yaml`

### Additional context

[Current BN <> VC Compatibility list tracker](https://github.com/kurtosis-tech/ethereum-package?tab=readme-ov-file#beacon-node--validator-client-compatibility)

Screenshot 2024-04-05 at 14 08 53

### Operating system

Linux

### Nimbus version or commit hash

`statusim/nimbus-eth2:multiarch-latest - sha256:8e79e02b37351bdcf0a4b07c9cb5a8dd23afdf83144a0d948644b72884cdd10d`

cc: @pk910

### PR DESCRIPTION
**Pull request by cheatfate**
This PR should fix #6176

### CODE REVIEW

File: beacon_chain/spec/eth2_apis/eth2_rest_serialization.nim [hunk 1]
```diff
@@ -3404,9 +3404,9 @@ proc writeValue*(writer: var JsonWriter[RestJson],
   withForkyMaybeBlindedBlck(value):
     writer.writeField("version", consensusFork.toString())
     when isBlinded:
-      writer.writeField("execution_payload_blinded", "true")
+      writer.writeField("execution_payload_blinded", true)
     else:
-      writer.writeField("execution_payload_blinded", "false")
+      writer.writeField("execution_payload_blinded", false)
```
Comment (tersec) [inline beacon_chain/spec/eth2_apis/eth2_rest_serialization.nim]: Could one replace the whole thing with `writer.writeField("execution_payload_blinded", isBlinded)` at this point? it doesn't seem like the conditional adds anything.
