### PR TITLE
Don't consider stubbed terminal block hash terminal (fixes #4094)

### LINKED ISSUE #4094: Missed proposal `getExecutionPayload: newExecutionPayload invalid`
**Describe the bug**
I've just missed a proposal on mainnet with the following Nimbus logs:
```
INF 2022-09-07 xx:xx:xx.xxx+xx:xx getExecutionPayload: newExecutionPayload invalid topics="beacval" executionPayloadStatus=ok(INVALID_BLOCK_HASH)
WRN 2022-09-07 xx:xx:xx.xxx+xx:xx Unable to get execution payload. Skipping block proposal topics="beacval" slot=xxxxxxx validator_index=xxxxxx
```

Geth showed this in its logs at the same time:
```
WARN [09-07|xx:xx:xx.xxx] Forkchoice requested update to zero hash
```

Mev-boost didn't show any logs at the time of proposal, but the closest lines were this:
```
time="2022-09-07Txx:xx:xx+xx:xx" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.2572213 method=GET module=service path=/eth/v1/builder/status status=200
time="2022-09-07Txx:xx:xx+xx:xx" level=info msg="http: POST /eth/v1/builder/validators 200" duration=0.128918712 method=POST module=service path=/eth/v1/builder/validators status=200
```

The connection between the EL and CL seems to be fine as I have both `Established connection to execution layer` and `Obtained terminal block from Engine API` in my logs on startup.

To be honest I didn't know mev-boost even did anything yet until the merge!

**To Reproduce**
1. Platform details (OS, architecture): Ubuntu 20.04.5 LTS ARM64 
2. Branch/commit used: v22.8.2

### PR DESCRIPTION
**Pull request by arnetheduck**

### CODE REVIEW

File: beacon_chain/eth1/eth1_monitor.nim [hunk 1]
```diff
@@ -586,8 +587,17 @@ proc exchangeTransitionConfiguration*(p: Eth1Monitor): Future[EtcStatus] {.async
          localValue = consensusCfg.terminalTotalDifficulty
     return EtcStatus.mismatch
 
+  if not p.exchangedConfiguration:
+    # Log successful engine configuration exchange once at startup
+    p.exchangedConfiguration = true
+    info "Exchanged engine configuration",
+      ttd = executionCfg.terminalTotalDifficulty,
+      terminalBlockHash = executionCfg.terminalBlockHash,
+      terminalBlockNumber = executionCfg.terminalBlockNumber.uint64
```
Comment (etan-status) [inline beacon_chain/eth1/eth1_monitor.nim:596]: This one is quite useful, also to verify that the EL connection is indeed working fine.

**Comment by etan-status** [comment]
Validated fix using `launch_local_testnet`.

**Comment by etan-status** [comment]
```
rm -rf local_testnet_data && scripts/launch_local_testnet.sh \
  --kill-old-processes --preset minimal --disable-htop --disable-vc --run-geth --dl-geth -- \
  --log-format=auto --max-peers=160
```
I ran this before this patch, and after this patch.

Without patch, network got stuck around block 17 and same message got logged about engine API usage. With patch, network proceeded as usual.
