### PR TITLE
Signature aggregation in block processing

### LINKED ISSUE #4: Potential incorrect serialization of  bls pub key
# Issue
_Note:_ I'm looking at Nim for the first time so this might just be incorrect.

The following defines a `BLSPubKey` which is used in the `ValidatorRecord` type definition
https://github.com/status-im/nim-beacon-chain/blob/ca4082b316689c8702dc8ba665611de31e3a92cf/beacon_chain/datatypes.nim#L63-L65

I believe that when you serialize `BLSPubKey` with SSZ that you will get a length prefix in the byte output. Because the length is known, we will likely use `int384` or `bytes48`. Both of these types will _not_ require a length prefix when serialized with SSZ.

_EDIT_
It looks like the items in this `aggregateSig` will suffer the same fate.
https://github.com/status-im/nim-beacon-chain/blob/ca4082b316689c8702dc8ba665611de31e3a92cf/beacon_chain/datatypes.nim#L77

Note, that while using the length of the `BLSPubKey` works for the bn256 curve for aggregate sig, if we use BLS12-381, the signatures are not the same length as the pub keys. One is 48bytes while the other is 96bytes (depending on if you G1 or G2 for the key).

### PR DESCRIPTION
**Pull request by mratsim**
This complete the following steps in [per-block-processing](https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ?view#Per-block-processing):

* Derive a group public key by adding the public keys of all of the attesters in attestation_indices for whom the corresponding bit in attester_bitfield (the ith bit is (attester_bitfield[i // 8] >> (7 - (i %8))) % 2) equals 1
* Verify that aggregate_sig verifies using the group pubkey generated and hash(slot.to_bytes(8, 'big') + parent_hashes + shard_id + shard_block_hash + justified_slot.to_bytes(8, 'big')) as the message.

## BLS keys and signatures

This should close #4, we might have a key length issue though, as in [Milagro we have the following](https://github.com/status-im/nim-milagro-crypto/blob/a6581e833d364b8372b15b500410edb27c4c7a36/src/scheme1.nim#L47-L50):

```Nim
const
  RawSignatureKeySize* = MODBYTES_384_29          # private key: 48 bytes
  RawVerificationKeySize* = MODBYTES_384_29 * 4   # public key: 192 bytes
  RawSignatureSize* = MODBYTES_384_29 * 2 + 1     # signature: 97 bytes (1 recovery byte?)
```

i.e. a BLS test suite is needed

## Message construction

The spec doesn't mention if the shard_id, an int16, should be interpreted as big or little endian before hashing. I assumed big endian.

A hash test suite would probably be helpful as well.

cc @djrtwo

### CODE REVIEW

**Comment by djrtwo** [comment]
Good point regarding big vs little endian. The python implementation of SSZ is explicitly using `"big"` when converting `int` to `bytes` representation:

https://github.com/ethereum/beacon_chain/blob/158dab0028812ba69ab17e2cd55f12b485c618ce/ssz/ssz.py#L10-L13

We'll go with big endian and be sure to make this very clear in the coming SSZ spec.

File: beacon_chain/state_transition.nim [hunk 1]
```diff
@@ -22,7 +22,7 @@
 
 import
   ./datatypes, ./private/helpers,
-  intsets,
+  intsets, endians, nimcrypto,
   milagro_crypto # nimble install https://github.com/status-im/nim-milagro-crypto@#master
```
Comment (djrtwo) [inline beacon_chain/state_transition.nim]: For the `parent_hashes` calculation, this was slightly modified in the spec (primarily the range is slightly different)

`[get_block_hash(active_state, block, slot - CYCLE_LENGTH + i) for i in range(1, CYCLE_LENGTH - len(oblique_parent_hashes) + 1)] + oblique_parent_hashes`

**Comment by mratsim** [comment]
Thanks I've updated to address all comments, beside the first one: use `parent.slot_number` instead of `block.slot_number`, I will need to keep a table of blocks hashed by their Blake2b hashes.
