### PR TITLE
Rewind and recovery for SyncManager.

### LINKED ISSUE #1153: IndexError after restart on witti
My node wasn't running for quite some while. Starting it again gave this error.  100% reproducable.

```
DBG 2020-06-09 15:31:11+02:00 Querying block number                      tid=144201 file=mainchain_monitor.nim:497 hash=099915f8fc1d2320795042fa631e349926e73f433977d214d084004a2aa7158a
DBG 2020-06-09 15:31:11+02:00 Received blocks on request                 topics="syncman" tid=144201 file=sync_manager.nim:860 blocks_count=1 blocks_map=.x.. peer=16Uiu2HAkvfDTKtFoSU5CHoA47BRwcJhN2zfvmr1kZXAwbweV3pq2 peer_score=200 request_count=4 request_slot=60982 request_step=1
DBG 2020-06-09 15:31:11+02:00 Forward sync imported blocks               topics="beacnde" tid=144201 file=beacon_node.nim:467 count=1 local_head_slot=60982
DBG 2020-06-09 15:31:11+02:00 Block received                             tid=144201 file=beacon_node_common.nim:100 blockRoot=ea46549e cat=block_listener pcs=receive_block signedBlock="(slot: 60983, proposer_index: 485, parent_root: \"c6567519\", state_root: \"97318553\", proposer_slashings_len: 0, attester_slashings_len: 0, attestations_len: 9, deposits_len: 0, voluntary_exits_len: 0)"
DBG 2020-06-09 15:31:11+02:00 Unresolved block (parent missing)          topics="clearblk" tid=144201 file=clearance.nim:240 blck="(slot: 60983, proposer_index: 485, parent_root: \"c6567519\", state_root: \"97318553\", proposer_slashings_len: 0, attester_slashings_len: 0, attestations_len: 9, deposits_len: 0, voluntary_exits_len: 0)" blockRoot=ea46549e cat=filtering missing=1 pcs=block_addition pending=1
DBG 2020-06-09 15:31:11+02:00 Block pool rejected peer's response        topics="beacnde" tid=144201 file=sync_manager.nim:516 blocks_count=1 blocks_map=.x.. errCode=MissingParent peer=16Uiu2HAkvfDTKtFoSU5CHoA47BRwcJhN2zfvmr1kZXAwbweV3pq2 request_count=4 request_slot=60982 request_step=1
 peers: 0 ❯ finalized: ffef3a02:1903 ❯ head: daa529d9:1905:22 ❯ time: 3051:23 (97655)                                                                                                                                                                                          ETH: 0 Traceback (most recent call last, using override)
/home/deme/repos/nim-beacon-chain/beacon_chain/mainchain_monitor.nim(516) main
/home/deme/repos/nim-beacon-chain/beacon_chain/mainchain_monitor.nim(509) NimMain
/home/deme/repos/nim-beacon-chain/beacon_chain/beacon_node.nim(1013) main
/home/deme/repos/nim-beacon-chain/beacon_chain/beacon_node.nim(763) start
/home/deme/repos/nim-beacon-chain/vendor/nim-chronicles/chronicles.nim(331) run
/home/deme/repos/nim-beacon-chain/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(407) reportUnhandledError
/home/deme/repos/nim-beacon-chain/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(358) reportUnhandledErrorAux
Error: unhandled exception: index out of bounds, the container is empty [IndexError]
```

Full log: https://gist.github.com/kdeme/53fb5f86c9cd068b762533d2a1b85982

### PR DESCRIPTION
**Pull request by cheatfate**
* Fix #1153.
* Add ability for SyncQueue to recover from unexpected `MissingParent`.

Recovery process is done using rewind to first slot of latest finalized epoch.

### CODE REVIEW

File: beacon_chain/beacon_node.nim [hunk 1]
```diff
@@ -542,6 +542,10 @@ proc runForwardSyncLoop(node: BeaconNode) {.async.} =
                 1'u64
     result = epoch.compute_start_slot_at_epoch()
 
+  proc getFirstSlotAtFinalizedEpoch(): Slot {.gcsafe.} =
```
Comment (arnetheduck) [inline beacon_chain/beacon_node.nim:545]: let's make this `getFinalizedCheckpoint` and it should return `node.blockPool.headState.data.data.finalized_checkpoint` - this is a general concept in the beacon chain world that will be useful elsewhere

Comment (cheatfate) [reply beacon_chain/beacon_node.nim:545]: @arnetheduck SyncManager operates with two low-level types `SignedBeaconBlock` and `Slot`. And this types are actually enough to perform syncing. Also infection of SyncManager with more types and more imports. Also it will significantly complicates testing...
