### PR TITLE
Fix add missing enr

### LINKED ISSUE #8272: ENR field `nfd` is missing
**Describe the bug**

Nimbus does not include the `nfd` (next fork digest) ENR field on Fulu-activated networks. The [consensus-specs](https://github.com/ethereum/consensus-specs/blob/v1.6.0-alpha.3/specs/fulu/p2p-interface.md#next-fork-digest) require this field to be present once `FULU_FORK_EPOCH != FAR_FUTURE_EPOCH`:

> This new entry MUST be added once `FULU_FORK_EPOCH` is assigned any value other than `FAR_FUTURE_EPOCH`.

> If no next fork is scheduled, the `nfd` entry contains the default value for the type (i.e., the SSZ representation of a zero-filled array).

Both Prysm and Lodestar include this field. Nimbus does not.

**To Reproduce**

## Version

`statusim/nimbus-eth2:multiarch-v26.3.0`

### Step 1: Launch a Fulu devnet

Save the following as `devnet.yaml`:

```yaml
participants:
  - el_type: geth
    cl_type: nimbus
    el_image: ethereum/client-go:v1.17.1
    cl_image: statusim/nimbus-eth2:multiarch-v26.3.0
    supernode: true
    validator_count: 32

  - el_type: geth
    cl_type: prysm
    el_image: ethereum/client-go:v1.17.1
    cl_image: offchainlabs/prysm-beacon-chain:v7.1.3
    supernode: true
    validator_count: 32

  - el_type: geth
    cl_type: lodestar
    el_image: ethereum/client-go:v1.17.1
    cl_image: chainsafe/lodestar:v1.41.0
    supernode: true
    validator_count: 32

network_params:
  network_id: "900010"
  num_validator_keys_per_node: 32
  electra_fork_epoch: 0
  fulu_fork_epoch: 0

additional_services:
  - dora
```

```bash
kurtosis run github.com/ethpandaops/ethereum-package \
  --args-file devnet.yaml \
  --enclave nfd-test
```

### Step 2: Get Beacon API ports

```bash
kurtosis enclave inspect nfd-test
```

Look for the `http` port mappings of the three CL clients. For example:

```
cl-1-nimbus-geth       http: 4000/tcp -> http://127.0.0.1:34414
cl-2-prysm-geth        http: 3500/tcp -> http://127.0.0.1:34417
cl-3-lodestar-geth     http: 4000/tcp -> http://127.0.0.1:34422
```

### Step 3: Compare ENRs

Wait ~30 seconds for the chain to start producing blocks, then query each client's ENR and look for the `nfd` key:

```bash
# Nimbus
curl -s http://127.0.0.1:<NIMBUS_PORT>/eth/v1/node/identity | jq -r '.data.enr'

# Prysm
curl -s http://127.0.0.1:<PRYSM_PORT>/eth/v1/node/identity | jq -r '.data.enr'
```

Base64-decode each ENR and RLP-decode to inspect the key-value pairs. The `nfd` key should be present in all three. Alternatively, use any ENR decoder (e.g., [enr-viewer](https://enr-viewer.com/)) to inspect the records.

This was verified across 16 consecutive snapshots (slots 1–16) — the field never appears on Nimbus.

**Additional context**
I'll add the PR later.

### PR DESCRIPTION
**Pull request by Alleysira**
## Summary

Fixes #8272.

Hello developers,

I have built a new docker image with the fix `alleysira/nimbus-eth2:nfd-fix`  and run in the kurtosis testnet, the fix works:
```
[13:24:25] Snapshot #1 | slot=0 epoch=0
 lodestar     nfd=00000000   peers=2   fork_digest=9992fd48 (zero, correct)
 nimbus       nfd=00000000   peers=2   fork_digest=9992fd48 (zero, correct)
 prysm        nfd=00000000   peers=2   fork_digest=9992fd48 (zero, correct)


[13:24:37] Snapshot #2 | slot=1 epoch=0
 lodestar     nfd=00000000   peers=2   fork_digest=9992fd48 (zero, correct)
 nimbus       nfd=00000000   peers=2   fork_digest=9992fd48 (zero, correct)
 prysm        nfd=00000000   peers=2   fork_digest=9992fd48 (zero, correct)


[13:24:49] Snapshot #3 | slot=2 epoch=0
 lodestar     nfd=00000000   peers=2   fork_digest=9992fd48 (zero, correct)
 nimbus       nfd=00000000   peers=2   fork_digest=9992fd48 (zero, correct)
 prysm        nfd=00000000   peers=2   fork_digest=9992fd48 (zero, correct)


[13:25:01] Snapshot #4 | slot=3 epoch=0
 lodestar     nfd=00000000   peers=2   fork_digest=9992fd48 (zero, correct)
 nimbus       nfd=00000000   peers=2   fork_digest=9992fd48 (zero, correct)
 prysm        nfd=00000000   peers=2   fork_digest=9992fd48 (zero, correct)
```

This is my first PR, please take a look, thanks!

### CODE REVIEW

File: beacon_chain/networking/eth2_network.nim [hunk 1]
```diff
@@ -1886,7 +1886,8 @@ proc new(T: type Eth2Node,
       config, ip, tcpPort, udpPort, privKey,
       {
         enrForkIdField: SSZ.encode(enrForkId),
-        enrAttestationSubnetsField: SSZ.encode(metadata.attnets)
+        enrAttestationSubnetsField: SSZ.encode(metadata.attnets),
+        enrNextForkDigestField: SSZ.encode(default(ForkDigest))
```
Comment (kdeme) [inline beacon_chain/networking/eth2_network.nim]: I don't think this should be set to 0, but instead be evaluating FULU_FORK_EPOCH as described by specs you link?

Comment (kdeme) [reply beacon_chain/networking/eth2_network.nim]: The logic exists here: https://github.com/status-im/nimbus-eth2/blob/102be79c06b408c4901fc73d92cbc8397c39425f/beacon_chain/networking/eth2_network.nim#L2741

and is called here https://github.com/status-im/nimbus-eth2/blob/102be79c06b408c4901fc73d92cbc8397c39425f/beacon_chain/nimbus_beacon_node.nim#L2129

But from first glance, it probably never updates it in the ENR because of the default value and the check here https://github.com/status-im/nimbus-eth2/blob/102be79c06b408c4901fc73d92cbc8397c39425f/beacon_chain/networking/eth2_network.nim#L2743

Comment (Alleysira) [reply beacon_chain/networking/eth2_network.nim]: Thanks for your attention, @kdeme.
Yes, I only set `nfd` to the default value at startup, since there are existing logic for updating the field.

Comment (Alleysira) [reply beacon_chain/networking/eth2_network.nim]: I run a quick test with kurtosis and this image `alleysira/nimbus-eth2:nfd-fix`, when `fulu_fork_epoch` is epoch `0` and `gloas_fork_epoch` is set to `1`. 

```
[16:53:19] Snapshot #1 | slot=0 epoch=0
 lodestar     nfd=a4d54326   peers=2   fork_digest=9992fd48
 nimbus       nfd=00000000   peers=2   fork_digest=9992fd48 (zero, correct)


[16:53:31] Snapshot #2 | slot=1 epoch=0
 lodestar     nfd=a4d54326   peers=2   fork_digest=9992fd48
 nimbus       nfd=00000000   peers=2   fork_digest=9992fd48 (zero, correct)


[16:53:43] Snapshot #3 | slot=2 epoch=0
 lodestar     nfd=a4d54326   peers=2   fork_digest=9992fd48
 nimbus       nfd=a4d54326   peers=2   fork_digest=9992fd48


[16:53:55] Snapshot #4 | slot=3 epoch=0
 lodestar     nfd=a4d54326   peers=2   fork_digest=9992fd48
 nimbus       nfd=a4d54326   peers=2   fork_digest=9992fd48


[16:54:07] Snapshot #5 | slot=4 epoch=0
 lodestar     nfd=a4d54326   peers=2   fork_digest=9992fd48
 nimbus       nfd=a4d54326   peers=2   fork_digest=9992fd48

```
With this fix, nimbus can successfully calculate and update `nfd`.

Comment (kdeme) [reply beacon_chain/networking/eth2_network.nim]: Yeah, what I was trying to explain in my first comment is that at the initialization it should already be set to the right value (so checking if there is a next scheduled fork or not, if not it can default to zeroes).

As you can see from your quick kurtosis test, for the first few slots the `nfd` is not filled in yet correctly (at least I think zero is not correct here), and only after slot 1 the  `nfd` value got updated as `updateNextForkDigest` must have kicked in and updated the value.

Comment (Alleysira) [reply beacon_chain/networking/eth2_network.nim]: Thanks for your explanation! I understand now and I will fix this by setting the right `nfd` in the startup.

**Comment by Alleysira** [comment]
## Kurtosis Test Results (2026-04-16)


Image tested: `alleysira/nimbus-eth2:nfd-fix-v2`
Reference clients: Lodestar v1.42.0, Teku (master)


### Scenario A: No next fork (Fulu only)

- `fulu_fork_epoch: 0`, no Gloas scheduled


**Result: PASS**


```
slot=5, epoch=0


Client         | fork_digest | nfd        | seq    | cgc
------------------------------------------------------------
Nimbus         | 6529b924    | 00000000   | 4      | 64
Lodestar       | 6529b924    | 00000000   | 7      | 128
teku           | 6529b924    | 00000000   | 10     | 128


PASS: all clients have nfd == 00000000
```


All three clients show `nfd=00000000` from the first snapshot. Nimbus `nfd` is no longer absent.


### Scenario B: Next fork scheduled (Fulu + Gloas at epoch 1)

- `fulu_fork_epoch: 0`, `gloas_fork_epoch: 1`, `genesis_delay: 300`
- Genesis delay ensures we can capture the ENR **before slot 0** and at every slot transition.


**Result: PASS**


**Slot 0** (pre-genesis, before any slot-end handler fires):


```
Client         | fork_digest | nfd        | seq    | cgc
------------------------------------------------------------
Nimbus         | 6529b924    | d0bc159b   | 4      | 64
Lodestar       | 6529b924    | d0bc159b   | 6      | 128
teku           | 6529b924    | d0bc159b   | 7      | 128


PASS: all clients agree on nfd == d0bc159b
```


**Slot 1**:


```
Client         | fork_digest | nfd        | seq    | cgc
------------------------------------------------------------
Nimbus         | 6529b924    | d0bc159b   | 4      | 64
Lodestar       | 6529b924    | d0bc159b   | 7      | 128
teku           | 6529b924    | d0bc159b   | 11     | 128


PASS: all clients agree on nfd == d0bc159b
```


**Slot 2**:


```
Client         | fork_digest | nfd        | seq    | cgc
------------------------------------------------------------
Nimbus         | 6529b924    | d0bc159b   | 5      | 64
Lodestar       | 6529b924    | d0bc159b   | 7      | 128
teku           | 6529b924    | d0bc159b   | 11     | 128


PASS: all clients agree on nfd == d0bc159b
```

**After Gloas activation, slot 31** (no next fork remaining):


```
Client         | fork_digest | nfd        | seq    | cgc
------------------------------------------------------------
Nimbus         | d0bc159b    | 00000000   | 37     | 64
Lodestar       | d0bc159b    | 00000000   | 10     | 128
teku           | d0bc159b    | 00000000   | 13     | 128


PASS: all clients have nfd == 00000000
```

PTAL, thanks!

File: beacon_chain/networking/eth2_network.nim [hunk 2]
```diff
@@ -1897,6 +1899,7 @@ proc new(T: type Eth2Node,
     announcedAddresses: @announcedAddresses,
     quota: TokenBucket.new(maxGlobalQuota, fullReplenishTime)
   )
+  node.nextForkDigest = initialNextForkDigest
```
Comment (kdeme) [inline beacon_chain/networking/eth2_network.nim]: It's cleaner to have this directly set in the `node` init right above here

**Comment by kdeme** [comment]
> 
> PTAL, thanks!

Yes, looks good now in terms of behaviour. Thanks for the kurtosis testing also.

I just left one small remark regarding how the `nextForkDigest` field gets set.

**Comment by Alleysira** [comment]
> I just left one small remark regarding how the `nextForkDigest` field gets set.

Thanks! Cleaned up as requested.

**Comment by tersec** [comment]
When the CI runs `make nimbus_light_client` it gets:
```
2026-04-16T13:13:15.7603700Z /Users/runner/work/nimbus-eth2/nimbus-eth2/beacon_chain/nimbus_light_client.nim(81, 29) template/generic instantiation of `createEth2Node` from here
2026-04-16T13:13:15.7707840Z /Users/runner/work/nimbus-eth2/nimbus-eth2/beacon_chain/networking/eth2_network.nim(2508, 22) template/generic instantiation of `new` from here
2026-04-16T13:13:15.7818480Z /Users/runner/work/nimbus-eth2/nimbus-eth2/beacon_chain/networking/eth2_network.nim(1901, 9) Error: identifier expected, but found 'node.nextForkDigest'
2026-04-16T13:13:16.6819020Z make: *** [nimbus_light_client] Error 1
2026-04-16T13:13:16.6951520Z make: *** Waiting for unfinished jobs....
```

**Comment by Alleysira** [comment]
> When the CI runs `make nimbus_light_client` it gets:

My local run of `make nimbus_light_client` is successful:
```
$ make nimbus_light_client
Git submodules not found. Running 'MSYS_NO_PATHCONV=1 git -c lfs.fetchexclude=/public-keys/all.txt,/metadata/genesis.ssz,/parsed/parsedConsensusGenesis.json submodule update --init --recursive'.
Building: Nim compiler
Building custom Nimble commit: 42ef70c2102a942c46f13eb76872326edd525cec
Building Nimble...
Replacing nimble binary...
Building: build/generate_makefile
Build completed successfully: build/generate_makefile
Building: build/nimbus_light_client
Build completed successfully: build/nimbus_light_client
```

File: beacon_chain/networking/eth2_network.nim [hunk 3]
```diff
@@ -2374,7 +2377,12 @@ proc createEth2Node*(
     wallEpoch = getBeaconTime().slotOrZero(cfg.timeParams).epoch
     enrForkId = cfg.getENRForkID(wallEpoch, genesis_validators_root)
     discoveryForkId = cfg.getDiscoveryForkID(wallEpoch, genesis_validators_root)
-
+    nextForkEpoch = cfg.nextForkEpochAtEpoch(wallEpoch)
+    initialNextForkDigest =
+      if nextForkEpoch == FAR_FUTURE_EPOCH:
+        default(ForkDigest)
+      else:
+        forkDigests[].atEpoch(nextForkEpoch, cfg)
```
Comment (tersec) [inline beacon_chain/networking/eth2_network.nim]: This duplicates the logic at
https://github.com/status-im/nimbus-eth2/blob/07d88087d0886b71711287e1049cb3599b3b3322/beacon_chain/nimbus_beacon_node.nim#L2088-L2098

To avoid duplication, it would be better to extract that as a helper function from its existing location and use the same helper function both to initialize and update. Furthermore, the spec URL should be updated to the current spec version https://github.com/ethereum/consensus-specs/blob/v1.7.0-alpha.5/specs/fulu/p2p-interface.md#next-fork-digest as I've checked that the exact phrasing has remained.

Especially with these sometimes odd-looking things (it's semi-arbitrary whether to go with `default(ForkDigest)` or not, ultimately), it's useful to clarify in the code that this is the only spec-compliant way of doing this.

Comment (tersec) [reply beacon_chain/networking/eth2_network.nim]: In both cases, the mapping is ultimately from `epoch` to `nextForkDigest`. Where that `nextForkDigest` is stored is what changes.

Comment (Alleysira) [reply beacon_chain/networking/eth2_network.nim]: Hi @tersec, thanks for your feedback! I have added a helper func and upated the spec url as requested. The local build also passed, please take a look.
```
$ make -j6 nimbus_beacon_node
Building: build/nimbus_beacon_node
Build completed successfully: build/nimbus_beacon_node
```

File: vendor/nim-lsquic
Comment (tersec) [inline vendor/nim-lsquic:1]: Why is this submodule updated?

File: vendor/nim-ssz-serialization
Comment (tersec) [inline vendor/nim-ssz-serialization:1]: Why is this submodule updated?

File: beacon_chain/networking/eth2_network.nim (hunk 3 above)
Comment (tersec) [reply beacon_chain/networking/eth2_network.nim]: https://github.com/status-im/nimbus-eth2/pull/8273/changes/821f1a1f4f89fc62461c16733b9b3fa57d0838a4#r3108497661 addresses this, yes.

File: vendor/nim-lsquic
Comment (Alleysira) [reply vendor/nim-lsquic:1]: > Why is this submodule updated?

Sorry for the mess, I didn't change the submodules. I think something is wrong during the merge, will look into this.

File: vendor/nim-ssz-serialization
Comment (tersec) [reply vendor/nim-ssz-serialization:1]: https://github.com/status-im/nimbus-eth2/pull/8273/changes/106dff736293c458a2a70cf40e78adb1a6505c1f

File: vendor/nim-lsquic
Comment (tersec) [reply vendor/nim-lsquic:1]: https://github.com/status-im/nimbus-eth2/pull/8273/changes/106dff736293c458a2a70cf40e78adb1a6505c1f
