### PR TITLE
sync fixes

### LINKED ISSUE #989: Peering issues with Prysm / Schlesi sync stuck
nim-beacon-chain devel @ 3ffd0d72168fa1aaf4aa81a2613f696d0ead51fb

Config:
```
beacon_node_shared_schlesi \
--log-level="DEBUG" \
--data-dir="/home/user/.opt/status-im/nim-beacon-chain/build/data/shared_schlesi" \
--web3-url="wss://goerli.infura.io/ws/v3/809a18497dd74102b5f37d25aae3c85a" \
--deposit-contract="0xA15554BF93a052669B511ae29EA21f3581677ac5" \
--bootstrap-file="/home/user/.opt/status-im/nim-beacon-chain/build/eth2-testnets/shared/schlesi/bootstrap_nodes.txt" \
--tcp-port=9876 \
--udp-port=9876 \
--state-snapshot="/home/user/.opt/status-im/nim-beacon-chain/build/eth2-testnets/shared/schlesi/genesis.ssz"
```

The initial sync of my Schlesi beacon node was interrupted and stalled after this:
```
INF 2020-05-07 14:29:34+02:00 Requesting detected missing blocks         topics="beacnde" tid=4076669 file=beacon_node.nim:471 missingBlocks="@[(root: EF071EDF09F5015B11A5DBFF858DA7A08F4F440D69EFCCE5D15614BC31EA7F1D, historySlots: 70579)]"
DBG 2020-05-07 14:29:34+02:00 Peer (incoming) lost                       topics="networking" tid=4076669 file=eth2_network.nim:637 peer="16Uiu2HAkvLCWwVEfF365ZWXB6siDL1mUpcd1XQ1nSXAHmvM5W7wn @[] @[]"
WRN 2020-05-07 14:29:34+02:00 unable to initiate pubsub                  tid=4076669 file=switch.nim:337 exc="Incomplete data received\nAsync traceback:\nException message: Incomplete data received\nException type:" topic=Switch
DBG 2020-05-07 14:29:34+02:00 Error, while waiting getBlocks response    topics="syncman" tid=4076669 file=sync_manager.nim:242 errMsg="Connection dead on arrival\nAsync traceback:\nException message: Connection dead on arrival\nException type:" peer=16Uiu2HAkvLCWwVEfF365ZWXB6siDL1mUpcd1XQ1nSXAHmvM5W7wn slot=2208 slot_count=32 step=1
DBG 2020-05-07 14:29:34+02:00 Failed to receive blocks on request        topics="syncman" tid=4076669 file=sync_manager.nim:356 peer=16Uiu2HAkvLCWwVEfF365ZWXB6siDL1mUpcd1XQ1nSXAHmvM5W7wn peer_score=4700 request_count=32 request_slot=2208 request_step=1
DBG 2020-05-07 14:29:34+02:00 Synchronization loop got worker finished   topics="syncman" tid=4076669 file=sync_manager.nim:461 local_head_slot=2207 peer=16Uiu2HAkvLCWwVEfF365ZWXB6siDL1mUpcd1XQ1nSXAHmvM5W7wn peer_score=4700 wall_head_slot=72768
DBG 2020-05-07 14:29:34+02:00 Synchronization loop end tick              topics="syncman" tid=4076669 file=sync_manager.nim:479 local_head_slot=2207 waiting_for_new_peer=true wall_head_slot=72768 workers_count=0
DBG 2020-05-07 14:29:34+02:00 Synchronization loop start tick            topics="syncman" tid=4076669 file=sync_manager.nim:387 local_head_slot=2207 queue_last_slot=72768 queue_start_slot=0 queue_status=3 wall_head_slot=72768 workers_count=0
DBG 2020-05-07 14:29:34+02:00 Synchronization loop waiting for new peer  topics="syncman" tid=4076669 file=sync_manager.nim:410 local_head_slot=2207 wall_head_slot=72768 workers_count=0
INF 2020-05-07 14:29:36+02:00 Slot start                                 topics="beacnde" tid=4076669 file=beacon_node.nim:337 beaconTime=872976 cat=scheduling finalizedEpoch=66 finalizedRoot=90d0b84c finalizedSlot=2112 headEpoch=68 headRoot=225c6229 headSlot=2207 lastSlot=72747 pcs=slot_start peers=0 scheduledSlot=72748
INF 2020-05-07 14:29:36+02:00 No head block update                       topics="blkpool" tid=4076669 file=block_pool.nim:872 cat=fork_choice head=225c6229:2207 pcs=fork_choice
NOT 2020-05-07 14:29:36+02:00 Node out of sync, skipping validator duties topics="beacval" tid=4076669 file=validator_duties.nim:363 headSlot=2207 slot=72748
INF 2020-05-07 14:29:36+02:00 Slot end                                   topics="beacnde" tid=4076669 file=beacon_node.nim:442 cat=scheduling finalizedEpoch=66 finalizedRoot=90d0b84c finalizedSlot=2112 headEpoch=68 headRoot=225c6229 headSlot=2207 nextSlot=72749 pcs=slot_start slot=72748
INF 2020-05-07 14:29:38+02:00 Requesting detected missing blocks         topics="beacnde" tid=4076669 file=beacon_node.nim:471 missingBlocks="@[(root: EF071EDF09F5015B11A5DBFF858DA7A08F4F440D69EFCCE5D15614BC31EA7F1D, historySlots: 70579)]"
DBG 2020-05-07 14:29:40+02:00 Failed to connect to peer                  topics="networking" tid=4076669 file=eth2_network.nim:720 err="Unable to connect to peer\nAsync traceback:\nException message: Unable to connect to peer\nException type:" peer=Node[75.172.0.5:12000]
DBG 2020-05-07 14:29:40+02:00 Discovered new peer                        topics="networking" tid=4076669 file=eth2_network.nim:714 peer=Node[5.252.224.98:12000]
DBG 2020-05-07 14:29:40+02:00 Connecting to peer                         topics="networking" tid=4076669 file=eth2_network.nim:682 peer="16Uiu2HAmRiNQUDa3t2RkpL8CatK7SMVtzdoKzGjDonmdzsvJ2AHn @[/ip4/5.252.224.98/tcp/13000] @[]"
WRN 2020-05-07 14:29:40+02:00 no handlers for                            tid=4076669 file=multistream.nim:152 protocol=/prysm/0.0.0/dht topic=Multistream
WRN 2020-05-07 14:29:40+02:00 no handlers for                            tid=4076669 file=multistream.nim:152 protocol=/eth2/beacon_chain/req/goodbye/1/ssz_snappy topic=Multistream
WRN 2020-05-07 14:29:40+02:00 ignored an error                           tid=4076669 file=errors.nim:62 multistream handle="multistream handle" name=LPStreamIncompleteError topic=Multistream
WRN 2020-05-07 14:29:40+02:00 ignored an error                           tid=4076669 file=errors.nim:62 multistream handle="multistream handle" name=LPStreamIncompleteError topic=Multistream
```

There's a lot going on in that log:
* pubsub: Incomplete data received
* getBlocks: Connection dead on arrival
* sync manager apparently unable to continue sync afterwards
* node out of sync
* failed to connect peer (Prysm?)
* no handlers for: goodbye (Prysm?)

After that it's an endless loop of:
```
NOT 2020-05-07 14:41:48+02:00 Node out of sync, skipping validator duties topics="beacval" tid=4076669 file=validator_duties.nim:363 headSlot=2527 slot=72809
INF 2020-05-07 14:41:48+02:00 Slot end                                   topics="beacnde" tid=4076669 file=beacon_node.nim:442 cat=scheduling finalizedEpoch=76 finalizedRoot=252d351d finalizedSlot=2432 headEpoch=78 headRoot=f2c65381 headSlot=2527 nextSlot=72810 pcs=slot_start slot=72809
INF 2020-05-07 14:42:00+02:00 Slot start                                 topics="beacnde" tid=4076669 file=beacon_node.nim:337 beaconTime=873720 cat=scheduling finalizedEpoch=76 finalizedRoot=252d351d finalizedSlot=2432 headEpoch=78 headRoot=f2c65381 headSlot=2527 lastSlot=72809 pcs=slot_start peers=0 scheduledSlot=72810
INF 2020-05-07 14:42:00+02:00 No head block update                       topics="blkpool" tid=4076669 file=block_pool.nim:872 cat=fork_choice head=f2c65381:2527 pcs=fork_choice
NOT 2020-05-07 14:42:00+02:00 Node out of sync, skipping validator duties topics="beacval" tid=4076669 file=validator_duties.nim:363 headSlot=2527 slot=72810
INF 2020-05-07 14:42:00+02:00 Slot end                                   topics="beacnde" tid=4076669 file=beacon_node.nim:442 cat=scheduling finalizedEpoch=76 finalizedRoot=252d351d finalizedSlot=2432 headEpoch=78 headRoot=f2c65381 headSlot=2527 nextSlot=72811 pcs=slot_start slot=72810
INF 2020-05-07 14:42:12+02:00 Slot start                                 topics="beacnde" tid=4076669 file=beacon_node.nim:337 beaconTime=873732 cat=scheduling finalizedEpoch=76 finalizedRoot=252d351d finalizedSlot=2432 headEpoch=78 headRoot=f2c65381 headSlot=2527 lastSlot=72810 pcs=slot_start peers=0 scheduledSlot=72811
INF 2020-05-07 14:42:12+02:00 No head block update                       topics="blkpool" tid=4076669 file=block_pool.nim:872 cat=fork_choice head=f2c65381:2527 pcs=fork_choice
NOT 2020-05-07 14:42:12+02:00 Node out of sync, skipping validator duties topics="beacval" tid=4076669 file=validator_duties.nim:363 headSlot=2527 slot=72811
INF 2020-05-07 14:42:12+02:00 Slot end                                   topics="beacnde" tid=4076669 file=beacon_node.nim:442 cat=scheduling finalizedEpoch=76 finalizedRoot=252d351d finalizedSlot=2432 headEpoch=78 headRoot=f2c65381 headSlot=2527 nextSlot=72812 pcs=slot_start slot=72811
INF 2020-05-07 14:42:24+02:00 Slot start                                 topics="beacnde" tid=4076669 file=beacon_node.nim:337 beaconTime=873744 cat=scheduling finalizedEpoch=76 finalizedRoot=252d351d finalizedSlot=2432 headEpoch=78 headRoot=f2c65381 headSlot=2527 lastSlot=72811 pcs=slot_start peers=0 scheduledSlot=72812
INF 2020-05-07 14:42:24+02:00 No head block update                       topics="blkpool" tid=4076669 file=block_pool.nim:872 cat=fork_choice head=f2c65381:2527 pcs=fork_choice
```

### PR DESCRIPTION
**Pull request by arnetheduck**
* fix Status message finalized info
* work around sync starting before initial status exchange
* don't fail block on deposit signature check failure (fixes #989)
* print ForkDigest and Version nicely
* dump incoming blocks
* fix crash when libp2p peer connection is closed

### CODE REVIEW

**Comment by tersec** [comment]
i.e. looks reasonable once it passes CI, via the `Error: Failed to convert to JSON an unsupported type: Version` issue

File: beacon_chain/spec/beaconstate.nim [hunk 1]
```diff
@@ -78,18 +81,17 @@ proc process_deposit*(
     # by the deposit contract
 
     # Fork-agnostic domain since deposits are valid across forks
-    #
-    # TODO zcli/zrnt does use the GENESIS_FORK_VERSION which can
-    # vary between minimal/mainnet, though, despite the comment,
-    # which is copied verbatim from the eth2 beacon chain spec.
-    # https://github.com/protolambda/zrnt/blob/v0.11.0/eth2/phase0/kickstart.go#L58
-    let domain = compute_domain(DOMAIN_DEPOSIT, GENESIS_FORK_VERSION)
```
Comment (tersec) [inline beacon_chain/spec/beaconstate.nim:86]: If this works in `tests/test_interop`, that's great. I remember adding this basically-workaround before, this the comment.

File: beacon_chain/spec/beaconstate.nim [hunk 2]
```diff
@@ -78,18 +81,17 @@ proc process_deposit*(
...
 
     let signing_root = compute_signing_root(deposit.getDepositMessage, domain)
     if skipBLSValidation notin flags and not bls_verify(
         pubkey, signing_root.data,
         deposit.data.signature):
-      return false
+      # It's ok that deposits fail - they get included in blocks regardless
+      # TODO spec test?
+      debug "Deposit signature verification failed",
+        pubkey, signing_root, signature = deposit.data.signature
```
Comment (tersec) [inline beacon_chain/spec/beaconstate.nim:93]: This would fix the observed issues with syncing with Schlesi, but just as a broader issue, it doesn't really matter why the deposit failed, the rest of the deposits should proceed: https://github.com/ethereum/eth2.0-specs/blob/v0.11.1/specs/phase0/beacon-chain.md#operations

File: beacon_chain/sync_manager.nim [hunk 3]
```diff
@@ -437,6 +437,12 @@ proc sync*[A, B](man: SyncManager[A, B]) {.async.} =
                     wall_head_slot = wallSlot, local_head_slot = headSlot,
                     peer_score = peer.getScore(), topics = "syncman"
               man.pool.release(peer)
+            elif not peer.hasInitialStatus:
+              # TODO Don't even consider these peers!
+              debug "Peer not ready", peer
```
Comment (protolambda) [inline beacon_chain/sync_manager.nim:442]: FYI: I'm hitting this on schlesi when running this PR

Comment (arnetheduck) [reply beacon_chain/sync_manager.nim:442]: yes, that's expected - this branch merely works around an underlying issue in the networking layer that needs more delicate attention - thanks for reporting though!

File: beacon_chain/spec/beaconstate.nim (hunk 1 above)
Comment (arnetheduck) [reply beacon_chain/spec/beaconstate.nim:86]: yeah, at some point were were not using `GENESIS_FORK_VERSION` everywhere where we should have been, but that's fixed which is why I suspect this works now

File: beacon_chain/spec/beaconstate.nim (hunk 2 above)
Comment (arnetheduck) [reply beacon_chain/spec/beaconstate.nim:93]: sure - I'm just hotfixing here, needs a spec test review as well
