### PR TITLE
don't convert URL to lower ascii, fixes #3756

### LINKED ISSUE #3756: Nimbus unexpectedly normalizes web3 RPC URLs
**Describe the bug**
I run Nimbus with `--web3-url=http://gateway.fm/ethereum/mainnet?apiKey=MyCaseSensitiveToKeN`

The requests I get on the gateway load balancer side have the URLs lowercased: `--web3-url=http://gateway.fm/ethereum/mainnet?apiKey=mycasesensitivetoken`.
That causes Nimbus to get 401 because tokens are case-sensitive.

At least in Teku & Prysm there is no problem with that.

**To Reproduce**
1. Platform details (OS, architecture): Linux x64, Docker container, official image: `statusim/nimbus-eth2:amd64-latest`
2. Branch/commit used: release `v22.5.2`3. 
3. add `--web3-url` parameter with a http url with the mix of capital and small letters
4. observe on the receiving side that all letters in the url are small.

### PR DESCRIPTION
**Pull request by narimiran**

### CODE REVIEW

File: beacon_chain/eth1/eth1_monitor.nim [hunk 1]
```diff
@@ -262,7 +262,7 @@ template finalizedDepositsMerkleizer(m: Eth1Monitor): auto =
   m.depositsChain.finalizedDepositsMerkleizer
 
 proc fixupWeb3Urls*(web3Url: var string) =
-  var normalizedUrl = toLowerAscii(web3Url)
+  var normalizedUrl = web3Url
```
Comment (arnetheduck) [inline beacon_chain/eth1/eth1_monitor.nim]: the `startsWith` comparisons below need to be case-insentive

Comment (narimiran) [reply beacon_chain/eth1/eth1_monitor.nim]: Ok, I've done it differently in the following commit.

**Review by arnetheduck — APPROVED** [review]
