### PR TITLE
verify `genesis_time` more strictly (fixes #1667)

### LINKED ISSUE #1667: [SEC] validator_client - unvalidated `genesis_time` can lead to validator client crash (int under/overflow)
## Description

on startup, the validator client connects to the beacon_node via `json-rpc` and requests `get_v1_beacon_genesis`. 

https://github.com/status-im/nim-beacon-chain/blob/c76305f824fbc6a61eca5bbb9d21002eb6c515e3/beacon_chain/validator_client.nim#L228-L232

The beacon node will respond with a message structured like this:

```
{
"jsonrpc":"2.0",
"id":2,
"result":{
  "genesis_time":<JINT>,
  "genesis_validators_root": {"data":<JARRAY(sizechecked)>},
    "genesis_fork_version":<JSTR>
    },
"error":null
}
```

While the response is implicitly syntactically verified, say, it unpacks to nim objects correctly or else throws (but keeps the validator alive), its contents are not verified semantically. For example, the validator node will accept and process any JINT returned by the server. This can be abused by a MitM to force the validator to process an invalid `genesis_time` (negative, > current time) to confuse it or provoke a crash.

#### Example

client
```
⇒  ./build/validator_client --rpc-address=127.0.0.1 --rpc-port=8885
DBG 2020-09-16 13:04:41.451+02:00 Launching validator client                 topics="vc" tid=3963057 file=validator_client.nim:208 version="0.5.0 (c76305f8)" cmdParams="@[\"--rpc-address=127.0.0.1\", \"--rpc-port=8885\"]" config="(logLevel: \"DEBUG\", logFile: None[OutFile], dataDir: /Users/tintin/Library/Application Support/Nimbus/BeaconNode, nonInteractive: false, validators: ..., validatorsDirFlag: None[InputDir], secretsDirFlag: None[InputDir], cmd: VCNoCommand, graffiti: None[GraffitiBytes], stopAtEpoch: 0, rpcPort: 8885, rpcAddress: 127.0.0.1, retryDelay: 10)"
INF 2020-09-16 13:04:41.452+02:00 Connected to BN                            topics="vc" tid=3963057 file=validator_client.nim:224 port=8885 address=127.0.0.1
DBG 2020-09-16 13:04:41.455+02:00 Message sent to RPC server                 topics="JSONRPC-HTTP-CLIENT" tid=3963057 file=httpclient.nim:188 address=127.0.0.1:8885 msg_len=69
/Users/tintin/workspace/nim/nim-beacon-chain-round3/vendor/nim-testutils/testutils/moduletests.nim(21) validator_client
/Users/tintin/workspace/nim/nim-beacon-chain-round3/beacon_chain/validator_client.nim(234) main
/Users/tintin/workspace/nim/nim-beacon-chain-round3/beacon_chain/time.nim(83) now
/Users/tintin/workspace/nim/nim-beacon-chain-round3/beacon_chain/time.nim(73) toBeaconTime
/Users/tintin/workspace/nim/nim-beacon-chain-round3/vendor/nimbus-build-system/vendor/Nim/lib/pure/times.nim(753) -
/Users/tintin/workspace/nim/nim-beacon-chain-round3/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: over- or underflow [OverflowError]
```

server: (Note: `genesis_time=-9223372036854775808` (int64_min))

```
Connection address: ('127.0.0.1', 51545)
received data: b'POST / HTTP/1.0\r\nDate: Wed, 16 Sep 2020 11:04:41 GMT\r\nHost: 127.0.0.1:8885\r\nContent-Type: application/json\r\nContent-Length: 69\r\n\r\n{"jsonrpc":"2.0","method":"get_v1_beacon_genesis","params":[],"id":1}'

send
HTTP/1.1 200 OK
Date: Wed, 16 Sep 2020 10:14:54 GMT
Content-Type: application/json
Content-Length: 266

{"jsonrpc":"2.0","id":1,"result":{"genesis_time":-9223372036854775808,"genesis_validators_root":{"data":[27,36,72,67,180,170,141,20,213,154,62,57,127,10,2,49,142,239,162,41,174,104,32,157,231,132,24,178,252,7,247,66]},"genesis_fork_version":"00000121"},"error":null}
nodata
```

## Exploit Scenario

Validator Client and NBC are communicating over an unsecured transport (TCP/HTTP; no TLS). A malicious third party may be able to MitM the connection, provide invalid values for `genesis_time` (or other fields) to confuse or crash the validator.

Note: we understand that the typical scenario is to run both clients on one system. However, it is likely that this will not be always the case, hence the beacon node/client split.

## Mitigation Recommendation

- strictly validate response parameters and check if they are with safe operating bounds for the application
- offer a transport secured communication channel and allow the validator client to authenticate the rpc-server.  (also noted in #1665)

### PR DESCRIPTION
**Pull request by arnetheduck**
Bogus values lead to crashes down the line when timers overflow

### CODE REVIEW

File: beacon_chain/libnimbus_lc/libnimbus_lc.nim [hunk 1]
```diff
@@ -240,9 +240,12 @@ proc ETHBeaconClockCreateFromState(
   ## * `state` - Beacon state.
   ##
   ## Returns:
-  ## * Pointer to an initialized beacon clock based on the beacon state.
+  ## * Pointer to an initialized beacon clock based on the beacon state or NULL
+  ##   if the state contained an invalid time
```
Comment (etan-status) [inline beacon_chain/libnimbus_lc/libnimbus_lc.nim]: The *.h file needs the same bump to the docs

File: beacon_chain/beacon_chain_db.nim [hunk 2]
```diff
@@ -1,5 +1,5 @@
 # beacon_chain
-# Copyright (c) 2018-2023 Status Research & Development GmbH
```
Comment (etan-status) [inline beacon_chain/beacon_chain_db.nim:2]: I find it sometimes useful to have some quick indicator to see how much a file has bitrotted since the last change.

Comment (arnetheduck) [reply beacon_chain/beacon_chain_db.nim:2]: meh, we have git for that which automates the process - this lint thing wastes a looot of mental (and CI) budget for the marginal value

File: beacon_chain/libnimbus_lc/libnimbus_lc.nim (hunk 1 above)
Comment (arnetheduck) [reply beacon_chain/libnimbus_lc/libnimbus_lc.nim]: bd7c34b1fe20678d3fa8123728bc62ee6330832c
