### PR TITLE
remove pre-Electra block production, attestation handling leftovers

### LINKED ISSUE #7795: Logs flooding with line Dropping aggregate
**Describe the bug**

The log `Dropping aggregate` from topics `beacval` in mode Debug don't bring any information and is filling the logs, making it difficult to debug. Could it be move to the level `TRACE` or remove entirely.

**To Reproduce**
1. Platform details (OS, architecture): linux x86 (but should be for every platform.
2. Branch/commit used: 25.11.0
3. Commands being executed: run the BN node normaly
4. Relevant log lines: `Dropping aggregate`

**Screenshots**

Image

**Additional context**

Improving the log visibility help the Node Operator, it's a small change that will make a lot of good in this cruel world !

### PR DESCRIPTION
**Pull request by arnetheduck**
https://github.com/status-im/nimbus-eth2/pull/7550 removed the ability to pack pre-Electra attestations in the attestation pool effectively removing the ability to create meaningful pre-Electra blocks - as such, there is little point in keeping the rest of the associated infrastructure around.

* refactor attestation pool to further remove phase0-based logic
* drop single-vote attestations after creating full committee aggregate
* simplify attestation cache key for block production (no need to include slot twice)
* avoid the use of `AttestationData` in `AttestationEntry` since they are no longer logically related (the latter is partitioned by committee index, the former is not)
* restore updates of last-voted-epoch for post-electra attestations and ignore duplicates based on it
* fix missing log data in "Dropping" logs (`logScope` does not work in generic functions) (fixes #7795)
* remove handlers/validators for pre-Electra attestation/aggregate gossip
* update gossip tests to cover post-Electra attestations
* remove pre-electra block production code paths in beacon node
* gossip fork checks based on message slot rather than wall time
* remove internal routing of on-chain attestation (obviously should never happen)

### CODE REVIEW

**Comment by tersec** [comment]
Merge conflict in `tests/test_attestation_pool.nim`

**Comment by arnetheduck** [comment]
[97da6c3](https://github.com/status-im/nimbus-eth2/pull/7959/commits/97da6c353fe13702cf4f2d22a0b36c66f3ab7c52)

File: beacon_chain/rpc/rest_validator_api.nim [hunk 1]
```diff
@@ -453,33 +453,11 @@ proc installValidatorApiHandlers*(router: var RestRouter, node: BeaconNode) =
...
-            forked, consensusFork, isBlinded = false,
-            message.executionValue, message.consensusValue,
-            node.hasRestAllowedOrigin)
-        else:
-          raiseAssert "preferredContentType() returns invalid content type"
       else:
         return RestApiResponse.jsonError(
           Http500, "Unsupported fork for block production: " & $consensusFork)
 
+  # https://ethereum.github.io/beacon-APIs/#/Validator/produceAttestationData
```
Comment (tersec) [inline beacon_chain/rpc/rest_validator_api.nim]: Duplicates the line following it?

Comment (arnetheduck) [inline beacon_chain/rpc/rest_validator_api.nim]:
```suggestion
```

**Comment by arnetheduck** [comment]
green at last! that mac os job is really quite annoying

**Comment by tersec** [comment]
> green at last! that mac os job is really quite annoying

Yes,
- https://github.com/status-im/nimbus-eth2/pull/7986

addresses part of it. But something is still going awry.
