### PR TITLE
Correct parsing of the `weak-subjectivity-checkpoint` parameter

### LINKED ISSUE #2776: Wrong weak-subjectivity-checkpoint parsing
**Describe the bug**
When using --weak-subjectivity-checkpoint, the argument is parsed wrongly:
    blockroot:epoch
the epoch is treated as ":epoch" (so with the colon)

**To Reproduce**
1. Platform details (OS, architecture): Windows 10
2. Branch/commit used: stable
3. Commands being executed: `./run-prater-beacon-node.sh --web3-url=(infura) --weak-subjectivity-checkpoint="0x3c1e98bf132530c669723f58aa3d395be0d0bfaa653152eecb04605`
e203bfeb5:31714"
4. Relevant log lines:
 `Error while processing the weak-subjectivity-checkpoint=0x3c1e98bf132530c669723f58aa3d395be0d0bfaa653152eecb04605e203bfeb5:31714 parameter: invalid unsigned integer: :31714`

Maybe related to #2530

### PR DESCRIPTION
**Pull request by zah**
Fixes #2776

### CODE REVIEW

File: beacon_chain/conf.nim [hunk 1]
```diff
@@ -958,11 +958,14 @@ func completeCmdArg*(T: type PubKey0x, input: string): seq[string] =
...
   let sepIdx = find(input, ':')
-  if sepIdx == -1:
+  if sepIdx == -1 or sepIdx == input.len - 1:
     raise newException(ValueError,
       "The weak subjectivity checkpoint must be provided in the `block_root:epoch_number` format")
-  T(root: Eth2Digest.fromHex(input[0 ..< sepIdx]),
-    epoch: parseBiggestUInt(input[sepIdx .. ^1]).Epoch)
+
+  var root: Eth2Digest
+  hexToByteArrayStrict(input[0 ..< sepIdx], root.data)
```
Comment (arnetheduck) [inline beacon_chain/conf.nim]:
```suggestion
  hexToByteArrayStrict(input.toOpenArray(0, sepIdx - 1), root.data)
```

File: beacon_chain/conf.nim [hunk 2]
```diff
@@ -958,11 +958,14 @@ func completeCmdArg*(T: type PubKey0x, input: string): seq[string] =
...
+
+  T(root: root, epoch: parseBiggestUInt(input[sepIdx + 1 .. ^1]).Epoch)
```
Comment (arnetheduck) [inline beacon_chain/conf.nim:968]:
```suggestion
  T(root: root, epoch: parseBiggestUInt(input.toOpenArray(sepIdx + 1, input.high)).Epoch)
```

**Review by arnetheduck — APPROVED** [review]

File: beacon_chain/conf.nim (hunk 2 above)
Comment (zah) [reply beacon_chain/conf.nim:968]: `parseBiggestUInt` expects a string unfortunately.
